version: "3.9"

services:
  web:
    build:
      context: ./flask-project
    image: flask-app:dev
    container_name: flask-app-dev
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - /Users/mack/algotest_task/flask-project:/app
    command: flask --app app run --host 0.0.0.0 --port 5000 --reload
