pipeline {
    agent any

    environment {
        REGISTRY = "registry.digitalocean.com"
        IMAGE_NAME = "flask-app"
        DOCKERFILE_PATH = "flask-project/Dockerfile"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'dev', 
                    url: 'https://github.com/harsh-madhav/task-terraform.git', 
                    credentialsId: 'git-credentials'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'docker-credentials',
                                                      usernameVariable: 'DOCKER_USER',
                                                      passwordVariable: 'DOCKER_PASS')]) {
                        sh '''
                            echo "$DOCKER_PASS" | docker login ${REGISTRY} -u "$DOCKER_USER" --password-stdin
                            docker build --platform linux/amd64 -t ${REGISTRY}/task-registry/${IMAGE_NAME}:${BUILD_NUMBER} flask-project
                            docker push ${REGISTRY}/task-registry/${IMAGE_NAME}:${BUILD_NUMBER}
                        '''
                    }
                }
            }
            post {
                failure {
                    echo "❌ Docker build failed"
                }
            }
        }

        stage('Trigger CD') {
            steps {
                build job: 'deployk8s/dev',
                    parameters: [
                        string(name: 'IMAGE_TAG', value: "${BUILD_NUMBER}")
                    ]
            }
        }
    }
}
