pipeline {
    agent any
    environment {
        REGISTRY = "registry.digitalocean.com/task-registry"   
        IMAGE_NAME = "flask-app"
        // DOCKER_HOST = 'tcp://docker:2376'
        // DOCKER_TLS_VERIFY = '1'
        // DOCKER_CERT_PATH = '/certs/client'
        DOCKERFILE_PATH = "flask-project/Dockerfile"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'dev', 
                     url: 'https://github.com/harsh-madhav/task-terraform.git', 
                     credentialsId: 'git-credentials'
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    // Change to the directory containing the Dockerfile
                    // Build Docker image
                    // sh "docker build -t ${REGISTRY}/${IMAGE_NAME}:${BUILD_NUMBER} -f ${DOCKERFILE_PATH} ."
                    // docker.withRegistry("https://${REGISTRY}", 'docker-credentials') {
                    //     sh "docker push ${REGISTRY}/${IMAGE_NAME}:${BUILD_NUMBER}"
                    //     sh "docker tag ${REGISTRY}/${IMAGE_NAME}:${BUILD_NUMBER} ${REGISTRY}/${IMAGE_NAME}:latest"
                    //     sh "docker push ${REGISTRY}/${IMAGE_NAME}:latest"
                    // }
                    sh 'docker --version'
                    sh 'docker ps'
                }
            }
            post {
                failure {
                    echo "Docker build failed"
                    // Add cleanup steps if needed
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry("https://${REGISTRY}", "docker-credentials") {
                        dockerImage.push()
                        dockerImage.push("latest")
                    }
                }
            }
            post {
                always {
                    // Clean up built images to save disk space
                    sh 'docker system prune -f'
                }
            }
        }
    }
}