namespace: task
replicas:
  - name: flask-app-task
    count: 1
images:
  - name: registry.digitalocean.com/task-registry/flask-app:latest

resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - serviceaccount.yaml
  - env.yaml  
